### ISSUE TITLE
Catel 4.0+

### ISSUE THREAD

**Issue by ruslan79k** [TimeCoder/DotNet#1]
Пример картотеки книг на новой версии Catel 4.0+ не работает уже, не могли бы вы исправить пример?

**Comment by TimeCoder** [comment]
Готово)
1. Выкинул все из класса App, сначала все, что в 4.1 перестало работать, затем вообще все - в данном примере там ничего не нужно. В модульном проекте там нужно инициализировать IoC контейнер и Bootstrapper.
2. Изменился способ привязки View ко ViewModel. Вообще их в Catel несколько: через аттрибуты класса, через code-behind View (используется в примере), или же вообще ничего не указывать (Catel сам их свяжет, если соблюдены правила именования, см. их сайт).
3. Почему-то теперь messageService.Show стал асинхронным. Пришлось добавить async/await-обвязку.
